### ISSUE TITLE
templates/profiles/ directory is missing profile_detail.html

### ISSUE THREAD

**Issue by andrewbt** [OpenTreeMap/otm-legacy#106]
The profile_detail.html template file is required/used when browsing to a specific user. ie, http://localhost/profiles/andrew/

**Comment by ghost** [comment]
In setting up OTM for the Montpelier (VT) Tree Board, I had made a profile_detail.html template you might use composed of the OTM edit_profile.html and a (somewhat incompatible) profile_detail.html from Josh Livni's repo. 

It has the bonus of fixing the display of Neighborhood names for recently changed trees, which is broken in OTM because it depends on a missing method(?) "sanfranciscotree". I also fixed the broken neighborhood display in results.html. Finally, in the two profile templates, I also added in the reputation change display from Josh's code which is missing in the official OTM. 

Actually I expanded on what was already in the OTM edit_profile to make profile_detail.html and edit_profile.html exactly identical, switching internally from display to edit modes. If profiles/urls.py were changed, both functions could be done by one file, but I didn't want to change any more than I had to, even though combining the files would be more in accord with DRY principles. 

One thing I couldn't fix, being too ignorant of Django, is the thumbnail display of the recently changed trees, since the profiles/model.py "recently_changed_trees" method used in the template tag seemingly doesn't produce an object that the foreign key in the treephoto object can join to correctly. (From this description you can tell how little I know!) 

What else I don't know is the proper procedure to contribute my example fix, being unused to Git (I used to use Subversion as a solitary developer). I have forked OTM and cloned my fork locally. I guess now I commit my change locally and push it to my forked remote origin, and you look at it on GitHub under rtroester/OpenTreeMap?

**Comment by andrewbt** [comment]
Hi Bob,

Looks like you actually have the Git workflow figured out pretty well. I would do all those things, and then if you want to go one step further (after pushing your local commit to your forked repo), would be to issue a "pull request" (that is done through the Github.com UI Pull Request button at the top, not from the git command line) from your forked copy to the main OpenTreeMap repository (remember we're on branch v1.3).

Depending on how significant a change it is when it comes through, we may ask you to sign a Contributor License Agreement - the PDF should be in the main OTM repository root.

**Comment by ghost** [comment]
Pull request 145 submitted.

**Comment by andrewbt** [comment]
Closing because https://github.com/azavea/OpenTreeMap/pull/145 deals with this issue and has been merged.
